app = "supply-chain-system-api"
primary_region = "syd"

[build]
  builder = "dockerfile"
  buildpacks = ["nodejs"]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true

[deploy]
  release_command = "npm run build"
  strategy = "immediate"

[processes]
  app = "node dist/main.js" 