app = "supply-chain-system-api"
primary_region = "syd"

[env]
  NODE_ENV = "production"
  PORT = "3001"
  # DATABASE_URL will be set via fly secrets

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[processes]
  app = "node dist/main"

[experimental]
  auto_rollback = true

[deploy.github]
  enabled = true
  repo = "syanix/SupplyChainSystem"
  branch = "main"
  auto_deploy = false 