app = "supply-chain-system-api-staging"
primary_region = "syd"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/nodejs"]
  [build.args]
    NODE_VERSION = "20"
    BUILD_COMMAND = "npm run build:all"
    PROJECT_PATH = "apps/api"

[experimental]
  enable_monorepo = true
  auto_rollback = true

[deploy]
  release_command = "npm run migration:run"
  strategy = "rolling"

[env]
  NODE_ENV = "staging"
  PORT = "3001"
  NPM_CONFIG_PRODUCTION = "true"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[processes]
  app = "npm run start:prod"

[deploy.github]
  enabled = true
  repo = "syanix/SupplyChainSystem"
  branch = "develop"
  auto_deploy = true 