name: Deploy API and Web

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      run_id:
        description: "GitHub Actions run ID containing the artifacts (optional)"
        required: false
        type: string
      build_id:
        description: "Build ID to deploy (optional)"
        required: false
        type: string
      confirm:
        description: 'Type "yes" to confirm deployment'
        required: true
        type: string
      deploy_api:
        description: "Deploy API to Fly.io"
        required: true
        default: true
        type: boolean
      deploy_web:
        description: "Deploy Web to Vercel"
        required: true
        default: true
        type: boolean

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        if: ${{ inputs.confirm != 'yes' }}
        run: |
          echo "Deployment not confirmed. Please set confirm input to 'yes' to proceed."
          exit 1

  trigger-api-deployment:
    needs: validate
    if: ${{ inputs.deploy_api }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-api.yml',
              ref: 'main',
              inputs: {
                environment: '${{ inputs.environment }}',
                run_id: '${{ inputs.run_id }}',
                build_id: '${{ inputs.build_id }}',
                confirm: 'yes'
              }
            });
            console.log('API deployment workflow triggered');

  trigger-web-deployment:
    needs: validate
    if: ${{ inputs.deploy_web }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Web Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-web.yml',
              ref: 'main',
              inputs: {
                environment: '${{ inputs.environment }}',
                run_id: '${{ inputs.run_id }}',
                build_id: '${{ inputs.build_id }}',
                confirm: 'yes'
              }
            });
            console.log('Web deployment workflow triggered');
