name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm deployment to staging'
        required: true
        default: "no"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation
        if: github.event.inputs.confirm != 'yes'
        run: |
          echo "Deployment not confirmed. Please type 'yes' to confirm."
          exit 1

  code-quality:
    needs: validate
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Check formatting
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,md,css,scss}"

  deploy-staging:
    needs: code-quality
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

        # Build packages first to ensure types are available
      - name: Build dependency packages
        run: npm run build:packages

      - name: Build
        run: npm run build

      # Create deployment artifact directory
      - name: Prepare deployment artifacts
        run: |
          mkdir -p deploy/apps/api/dist
          mkdir -p deploy/packages/database/dist
          mkdir -p deploy/packages/shared/dist
          mkdir -p deploy/packages/ui/dist

          # Copy necessary files
          cp -r apps/api/dist/* deploy/apps/api/dist/
          cp -r packages/database/dist/* deploy/packages/database/dist/
          cp -r packages/shared/dist/* deploy/packages/shared/dist/
          cp -r packages/ui/dist/* deploy/packages/ui/dist/
          cp apps/api/Dockerfile deploy/
          cp apps/api/package.json deploy/apps/api/
          cp packages/database/package.json deploy/packages/database/
          cp packages/shared/package.json deploy/packages/shared/
          cp packages/ui/package.json deploy/packages/ui/
          cp package.json deploy/

      # Install Fly CLI
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy to Fly.io
      - name: Deploy API to Fly.io (Staging)
        run: |
          cd deploy
          flyctl deploy --config ../apps/api/fly.staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy Web to Vercel (Staging)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
          root-directory: .
          vercel-args: "--prod --prebuilt"
