name: CI/CD Pipeline

on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main, staging, development]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # For push events, only run the check script
      - name: Run check (push)
        if: github.event_name == 'push'
        run: npm run check

      # For pull requests, run the full build and test process
      - name: Build Depedency packages (PR)
        if: github.event_name == 'pull_request'
        run: npm run build:packages

      - name: Build (PR)
        if: github.event_name == 'pull_request'
        run: npm run build
